import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import type { UiLocale } from './types';

const STORAGE_KEY = 'agentlab.ui.locale.v1';
const locales: UiLocale[] = ['en', 'zh-CN'];

export const readLocale = (storage: Pick<Storage, 'getItem'> | undefined = typeof localStorage === 'undefined' ? undefined : localStorage, browserLanguage = typeof navigator === 'undefined' ? 'en' : navigator.language): UiLocale => {
  if (storage) {
    try { const saved = storage.getItem(STORAGE_KEY) as UiLocale | null; if (saved && locales.includes(saved)) return saved; } catch { /* Fall through to browser detection. */ }
  }
  return browserLanguage.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en';
};

export const persistLocale = (locale: UiLocale) => {
  if (typeof localStorage !== 'undefined') try { localStorage.setItem(STORAGE_KEY, locale); } catch { /* Keep the in-memory locale. */ }
  if (typeof document !== 'undefined') document.documentElement.lang = locale;
};

const zh: Record<string, string> = {
  'design validation workspace': 'Agent 设计验证工作台', 'Runner online': 'Runner 在线', 'Local mode': '本地模式', Help: '帮助', Settings: '设置', Workspace: '工作区', Projects: '项目', Templates: '模板', Documentation: '文档', BUILD: '构建', Blocks: '积木', 'Import Python block': '导入 Python 积木', 'Start from template': '从模板开始', 'Choose a tested topology': '选择经过验证的拓扑', 'Search blocks': '搜索积木', 'Template library': '模板库', Design: '设计', Runs: '运行记录', Evaluations: '评测', Versions: '版本', 'Unsaved changes': '有未保存更改', 'All changes saved': '所有更改已保存', Undo: '撤销', Redo: '重做', Cut: '剪切', Copy: '复制', Paste: '粘贴', Duplicate: '复制副本', Delete: '删除', Validate: '校验', Stop: '停止', Run: '运行', Save: '保存', 'Import project': '导入项目', 'Export project': '导出项目', 'Export code': '导出代码', 'Design canvas': '设计画布', blocks: '个积木', connections: '条连线', 'drag to pan': '拖动平移', 'scroll to zoom': '滚动缩放', 'Use a larger viewport to edit': '请使用更大的窗口进行编辑', "Agent Lab's canvas is optimized for 1280px and above. You can still inspect runs on mobile.": 'Agent Lab 画布针对 1280px 及以上宽度优化；移动端仍可查看运行记录。',
  'Restoring workspace': '正在恢复工作区', 'Graph is valid': '图校验通过', 'Local validation passed': '本地校验通过', 'Revision saved': '版本已保存', 'Saved locally; runner unavailable': 'Runner 不可用，已在本地标记保存', 'Export downloaded': '导出文件已下载', 'Saved local project JSON': '已保存本地项目 JSON', 'Project imported': '项目已导入', 'Import failed': '导入失败', 'Python block imported': 'Python 积木已导入', 'Imported; Docker/Podman required to run': '已导入；运行需要 Docker/Podman', 'Python import failed': 'Python 导入失败', 'Remote run completed.': '远程运行已完成。', 'Runner event stream failed. Inspect the run record before retrying.': 'Runner 事件流失败，请检查运行记录后重试。', 'Remote run failed': '远程运行失败', 'Local simulation completed. Connect a runner for live model calls.': '本地模拟已完成；连接 Runner 后可调用真实模型。', 'Run cancelled by user.': '用户已取消运行。',
  'Select a block': '请选择积木', 'Configure its inputs, edit instance code, or inspect ports and docs.': '可配置输入、编辑实例代码，或查看端口和文档。', Config: '配置', Code: '代码', Ports: '端口', Docs: '文档', 'INSTANCE OVERRIDE': '实例覆盖代码', 'CATALOG CODE': '目录原始代码', Reset: '重置', 'Display name': '显示名称', 'Block description': '积木描述', 'Runtime config': '运行配置', 'This block has no custom configuration.': '此积木没有自定义配置。', 'Sandbox policy': '沙箱策略', 'No elevated permissions': '无额外权限', Inputs: '输入端口', Outputs: '输出端口', 'Catalog reference': '目录参考', 'Imported block': '导入的积木', Capabilities: '能力', 'typed ports': '类型化端口', 'container execution': '容器执行', Console: '控制台', Trace: '追踪', Io: '输入/输出', Metrics: '指标', Problems: '问题', 'No trace events yet': '暂无追踪事件', 'Run the graph to inspect each lifecycle span.': '运行图后可查看各生命周期 Span。', Input: '输入', Output: '输出', 'No output yet.': '暂无输出。', 'Total tokens': '总 Token', 'Wall time': '耗时', 'Est. cost': '预估费用', 'Tool calls': '工具调用', 'No problems': '没有问题', 'Validation issues will appear here.': '校验问题会显示在这里。',
  Appearance: '外观', Providers: 'Provider', 'Device preferences': '设备偏好', 'DEVICE DISPLAY': '设备显示', 'LOCAL SECRETS': '本地密钥', 'Model providers': '模型 Provider', 'This preference applies to this browser and is not saved with projects.': '该偏好只应用于此浏览器，不会写入项目。', 'Keys stay in the local runner and are never returned to the browser.': 'Key 保存在本地 Runner 中，绝不会返回浏览器。', 'Close settings': '关闭设置', 'Interface text size': '界面文字大小', 'Canvas nodes, graph controls and the code editor retain their own scale.': '画布节点、图控件和代码编辑器保持独立字号。', Compact: '紧凑', Default: '默认', Comfortable: '舒适', Large: '大号', 'Device-level preference': '设备级偏好', 'Stored with a versioned local schema. Invalid or older values safely reset to 100%.': '使用版本化本地结构保存；无效或旧数据会安全回退到 100%。', Language: '语言', 'Choose the interface language for this browser.': '选择此浏览器使用的界面语言。', English: 'English', Chinese: '中文', 'Persist in the operating system keychain': '持久保存到操作系统 Keychain', 'Loading providers': '正在加载 Provider', Configured: '已配置', 'Not configured': '未配置', 'Enter API key': '输入 API Key', 'Default model': '默认模型', 'Used when an LLM node leaves its model field empty.': '当 LLM 节点的模型字段留空时使用。', 'Save key': '保存 Key', 'Save model': '保存模型', 'Remove credential': '删除凭据', 'Project exports do not contain display settings': '项目导出不包含显示设置', 'Project files store provider references only': '项目文件只保存 Provider 引用', Done: '完成',
  OBSERVE: '观察', 'Run history': '运行历史', 'Runs are pinned to immutable server revision IDs.': '运行记录绑定到不可变的服务端 Revision ID。', 'Export CSV': '导出 CSV', Revision: '版本', Status: '状态', Started: '开始时间', Duration: '耗时', 'Loading runs': '正在加载运行记录', 'Reading persisted run records from the runner.': '正在从 Runner 读取持久运行记录。', 'Runs unavailable': '运行记录不可用', 'The runner does not expose the project runs endpoint yet.': 'Runner 暂时无法提供项目运行接口。', 'No runs recorded': '暂无运行记录', 'Run the current revision to create the first persistent trace.': '运行当前版本以创建第一条持久 Trace。',
  HISTORY: '历史', 'Select one baseline and one candidate revision.': '请选择一个基线版本和一个候选版本。', 'A/B evaluate': 'A/B 评测', Compare: '对比', 'Save the project first': '请先保存项目', 'Version comparison requires immutable server revision IDs.': '版本对比需要不可变的服务端 Revision ID。', 'Loading revisions': '正在加载版本', 'Reading immutable project history.': '正在读取不可变项目历史。', 'Revisions unavailable': '版本不可用', 'Could not read revision history from the runner.': '无法从 Runner 读取版本历史。', 'Baseline A': '基线 A', 'Candidate B': '候选 B', Checkpoint: '检查点', 'Secret-like config and code values are redacted': '配置和代码中的敏感值已脱敏', Added: '新增', Removed: '删除', Modified: '修改', 'Layout only': '仅布局', Edges: '连线', 'No block changes.': '没有积木变化。', 'Baseline config': '基线配置', 'Candidate config': '候选配置', 'Baseline code override': '基线覆盖代码', 'Candidate code override': '候选覆盖代码',
  VERIFY: '验证', 'A/B evaluations': 'A/B 评测', 'Compare immutable revisions against a reusable test suite.': '使用可复用测试集比较不可变版本。', 'Import JSON': '导入 JSON', 'New suite': '新建测试集', 'Start comparison': '开始对比', 'Baseline revision': '基线版本', 'Select baseline A': '选择基线 A', 'Candidate revision': '候选版本', 'Select candidate B': '选择候选 B', 'Evaluation suite': '评测集', 'Select suite': '选择评测集', 'Max cases': '最大 Case 数', 'Max tokens': '最大 Token', 'Max cost USD': '最大费用 USD', 'Wall seconds': '最长秒数', 'paired runs maximum': '次配对运行上限', 'Simulator runs are always available. Real-provider A/B requires an exact model snapshot in the runner price registry; aliases and unknown models fail closed.': '模拟器始终可用。真实 Provider A/B 要求 Runner 价格表中的精确模型快照；别名和未知模型会安全拒绝。', 'Start A/B evaluation': '开始 A/B 评测', 'Could not start evaluation.': '无法启动评测。', 'Evaluation suites': '评测集', cases: '个 Case', 'paired assertions': '配对断言', 'Create or import a suite to begin.': '创建或导入评测集后开始。', Experiments: '实验', 'Loading evaluations': '正在加载评测', 'No evaluations yet': '暂无评测', 'Configure revisions and a suite, then start the first comparison.': '配置版本和评测集后开始第一次对比。', 'Select an experiment': '请选择实验', 'Results, paired metrics and assertion failures appear here.': '结果、配对指标和断言失败信息会显示在这里。', Cancel: '取消', 'Baseline pass': '基线通过率', 'Candidate pass': '候选通过率', Improvements: '改进', Regressions: '回退', Case: 'Case', 'A pass': 'A 通过', 'B pass': 'B 通过', Tokens: 'Token', 'Baseline output': '基线输出', 'Candidate output': '候选输出', 'No output': '无输出', 'PERSISTENT DATASET': '持久数据集', 'Edit evaluation suite': '编辑评测集', 'New evaluation suite': '新建评测集', 'Cases and assertions are saved independently from project revisions.': 'Case 和断言独立于项目版本保存。', Name: '名称', Description: '描述', 'Test cases': '测试 Case', 'paired inputs': '组配对输入', 'Add case': '添加 Case', 'Input / JSON': '输入 / JSON', 'Expected / JSON': '期望 / JSON', Assertion: '断言', 'Delete suite': '删除评测集', 'Save suite': '保存评测集',
  'STARTER KIT': '入门套件', 'Choose a design pattern': '选择设计模式', 'Each template is a runnable baseline you can freely adapt.': '每个模板都是可自由修改的可运行基线。', 'Search templates': '搜索模板', Starter: '入门', Intermediate: '中级', Advanced: '高级', 'Templates include editable instance code': '模板包含可编辑的实例代码',
  'Input / Output': '输入 / 输出', 'LLM & Prompt': 'LLM 与提示词', 'Control Flow': '控制流', 'Tools & MCP': '工具与 MCP', 'State & Memory': '状态与记忆', Guardrails: '护栏', Evaluation: '评测', 'Harness Hooks': 'Harness Hook',
  'User Input': '用户输入', 'Accept a prompt or structured request.': '接收提示词或结构化请求。', 'Entry point for a run. Pass text or JSON from the input panel.': '运行入口；从输入面板传入文本或 JSON。', 'Chat Model': '对话模型', 'Call a provider through the secure model gateway.': '通过安全模型网关调用 Provider。', 'Provider-agnostic model call. Secrets stay outside the sandbox.': '与 Provider 无关的模型调用；密钥始终位于沙箱之外。', 'ReAct Loop': 'ReAct 循环', 'Alternate reasoning and tool use until a final answer.': '交替执行推理与工具调用，直到得到最终答案。', 'Bounded loop with explicit max steps, timeout and tool budget.': '具有明确最大步数、超时和工具预算的受限循环。', 'Plan & Execute': '规划与执行', 'Create a plan, execute steps, then synthesize.': '创建计划、执行步骤并综合结果。', 'Separate planning, execution, and synthesis.': '分离规划、执行和综合阶段。', 'Router': '路由器', 'Route each request to a specialist path.': '将请求路由到专业处理路径。', 'Use named routes and fallback handling for specialist agents.': '使用命名路由和回退策略管理专业 Agent。', Supervisor: '监督者', 'Coordinate specialist agents with a shared task state.': '使用共享任务状态协调专业 Agent。', 'Memory Store': '记忆存储', 'Persist and retrieve relevant run context.': '持久化并检索相关运行上下文。', 'HTTP Request': 'HTTP 请求', 'Call an allow-listed HTTP endpoint.': '调用允许列表中的 HTTP 端点。', 'MCP Server': 'MCP 服务', 'Expose tools from a Model Context Protocol server.': '公开 Model Context Protocol 服务提供的工具。', 'Human Approval': '人工审批', 'Pause before an irreversible action.': '在不可逆操作前暂停并等待审批。', 'Policy Gate': '策略门', 'Check input or output against a policy.': '根据策略检查输入或输出。', 'Trace Hook': '追踪 Hook', 'Capture lifecycle spans and state diffs.': '捕获生命周期 Span 和状态差异。', 'Context Compact': '上下文压缩', 'Summarize context when the budget is reached.': '达到预算时压缩上下文。', Evaluator: '评估器', 'Score output with assertions or a judge.': '使用断言或 Judge 为输出评分。', 'Final Answer': '最终答案', 'Return a user-facing answer.': '返回面向用户的答案。',
  'Tool Use Starter': '工具调用入门', 'A minimal model + tool path for calling APIs safely.': '安全调用 API 的最小模型与工具路径。', 'Reason, act, observe and stop inside a bounded control block.': '在受限控制积木中进行思考、行动、观察和停止。', 'Plan-and-Execute': '规划与执行', 'Route requests to specialist paths with a safe fallback.': '将请求路由到专业路径并提供安全回退。', 'Supervisor Team': '监督者团队', 'A supervisor dispatches work to parallel specialist workers.': '由监督者向并行专业 Worker 分派工作。', 'Memory Agent': '记忆 Agent', 'Retrieve context, answer, and persist a useful memory.': '检索上下文、生成答案并保存有用记忆。', 'Harness Evolution Lab': 'Harness 演进实验室', 'Twenty progressively layered harness capabilities with explicit dependency order.': '二十项按明确依赖顺序逐层组合的 Harness 能力。',
};

Object.assign(zh, {
  'Tool Use / Augmented LLM': '工具调用 / 增强型 LLM', ReAct: 'ReAct', 'Supervisor / Multi-agent': '监督者 / 多 Agent', 'Memory-augmented': '记忆增强', 's01-s20 Harness mechanisms': 's01-s20 Harness 机制',
  'Could not save provider setting': '无法保存 Provider 设置', 'Default model saved': '默认模型已保存',
  'Agent Lab ready. Load a template or add a block to begin.': 'Agent Lab 已就绪，请加载模板或添加积木。', 'Find a concise answer and cite the sources you used.': '给出简洁答案，并引用所使用的来源。', 'Restored the last saved project.': '已恢复上次保存的项目。', Loaded: '已加载', 'Run validation before execution.': '执行前请先校验。', Added: '已添加', 'Run completed successfully.': '运行成功完成。', 'Ready for a new run.': '已准备开始新的运行。',
  'Compatible lifecycle': '兼容生命周期', 'Platform sandbox and secret protection remain outside removable blocks.': '平台沙箱和密钥保护始终位于可移除积木之外。',
  Run: '运行', connections: '条连线', 'No ports exposed.': '没有公开端口。', 'Graph has validation errors.': '图存在校验错误。', 'Add at least an input and an output block.': '请至少添加一个输入积木和一个输出积木。', 'Connect blocks before running.': '运行前请先连接积木。', 'Could not save evaluation.': '保存失败。', 'Save the project before evaluating': '评测前请先保存项目', 'A/B evaluation requires two immutable server revisions and a persistent evaluation suite.': 'A/B 评测需要两个不可变服务端版本和一个持久评测集。', 'Configure revisions and a suite, then start the first comparison.': '配置版本和评测集后开始第一次对比。', 'Results, paired metrics and assertion failures appear here.': '结果、配对指标和断言失败信息会显示在这里。', 'Imported suite': '导入的评测集', 'Local Python source snapshot.': '本地 Python 源码快照。', 'not selected': '未选择', 'credential removed': '凭据已删除', 'Could not remove': '无法删除',
  LLM: 'LLM', Tools: '工具', Control: '控制', Loop: '循环', Planning: '规划', 'Multi-path': '多路径', Routing: '路由', Agents: 'Agent', Parallel: '并行', Memory: '记忆', RAG: 'RAG', Harness: 'Harness', 's01-s20': 's01-s20',
  'Separate planning from execution for inspectable multi-step tasks.': '将规划与执行分离，以便检查多步骤任务。', 'Delegates work and merges specialist outputs with a supervisor policy.': '使用监督策略分派工作并合并专业 Agent 输出。', 'Memory is explicit state. Choose a backend and retention policy.': '记忆是显式状态；请选择后端和保留策略。', 'Network access is disabled unless a domain is explicitly approved.': '除非域名获得明确批准，否则网络访问保持禁用。', 'MCP tools run with declared permissions and are included in the trace.': 'MCP 工具按声明权限运行，并记录在 Trace 中。', 'Require a human decision before a tool or state mutation.': '在工具调用或状态变更前要求人工决策。', 'Fail closed when a policy is unavailable or ambiguous.': '策略不可用或含糊时安全拒绝。', 'Attach to a lifecycle slot to make execution inspectable.': '挂载到生命周期位置，使执行过程可检查。', 'Keep long-running agents within a predictable context budget.': '让长时间运行的 Agent 保持在可预测的上下文预算内。', 'Use this block for exact, schema, trajectory or LLM-as-judge checks.': '使用此积木执行精确、Schema、轨迹或 LLM-as-judge 检查。', 'Terminal output shown in the run panel.': '终端输出会显示在运行面板中。',
  'S01 Agent Loop': 'S01 Agent 循环', 'Core model/tool execution loop': '核心模型与工具执行循环', 'S02 Tool Registry': 'S02 工具注册表', 'Typed tool schemas and handler dispatch': '类型化工具 Schema 与处理器分发', 'S03 Permission Gate': 'S03 权限门', 'Deny, allow and approval policies': '拒绝、允许与审批策略', 'S04 Lifecycle Hooks': 'S04 生命周期 Hook', 'Stable extension points around execution': '执行前后的稳定扩展点', 'S05 Todo Planning': 'S05 待办规划', 'Persistent bounded task planning': '持久且受限的任务规划', 'S06 Subagent': 'S06 子 Agent', 'Fresh-context delegated execution': '使用全新上下文进行委派执行', 'S07 Skill Loading': 'S07 Skill 加载', 'Load domain knowledge on demand': '按需加载领域知识', 'S08 Context Compact': 'S08 上下文压缩', 'Reduce context before budget overflow': '预算溢出前缩减上下文', 'S09 Memory': 'S09 记忆', 'Select, extract and consolidate memory': '选择、提取并整合记忆', 'S10 Prompt Assembly': 'S10 Prompt 组装', 'Build runtime prompts from sections': '从分段内容构建运行时 Prompt', 'S11 Error Recovery': 'S11 错误恢复', 'Retry, compact or select another path': '重试、压缩或选择其他路径', 'S12 Task Graph': 'S12 任务图', 'Persist tasks and dependencies': '持久化任务与依赖', 'S13 Background Tasks': 'S13 后台任务', 'Run slow operations asynchronously': '异步运行耗时操作', 'S14 Cron Trigger': 'S14 定时触发器', 'Start runs from a bounded schedule': '通过受限计划启动运行', 'S15 Agent Teams': 'S15 Agent 团队', 'Create persistent specialist teammates': '创建持久专业队友', 'S16 Team Protocols': 'S16 团队协议', 'Structured request and response messages': '结构化请求与响应消息', 'S17 Autonomous Claim': 'S17 自主领取', 'Let workers claim eligible tasks': '允许 Worker 领取符合条件的任务', 'S18 Workspace Isolation': 'S18 工作区隔离', 'Bind tasks to isolated workspaces': '将任务绑定到隔离工作区', 'S19 MCP Connector': 'S19 MCP 连接器', 'Add external tools through MCP': '通过 MCP 添加外部工具', 'S20 Comprehensive Harness': 'S20 综合 Harness', 'Composite reference of all mechanisms': '所有机制的组合参考实现',
});

Object.assign(zh, {
  'Discard unsaved changes and open this project?': '放弃未保存的更改并打开该项目吗？', 'Project opened': '项目已打开', 'Could not open project': '无法打开项目',
  'Saved with credential warnings; check Problems': '已保存，但存在凭据警告；请查看问题面板', 'Export blocked: credential-like data found': '导出被阻止：发现疑似凭据内容', 'Export anyway?': '仍要导出吗？', 'Export cancelled': '已取消导出', Cost: '费用',
  WORKSPACE: '工作区', 'Saved projects live in the local runner database.': '已保存的项目存放在本地 Runner 数据库中。', 'Loading projects': '正在加载项目', 'Projects unavailable': '项目列表不可用', 'Could not read the project list from the runner.': '无法从 Runner 读取项目列表。', 'No description': '暂无描述', CURRENT: '当前', 'Rename project': '重命名项目', 'Delete project': '删除项目', 'Could not rename project': '无法重命名项目', 'Could not delete project': '无法删除项目', 'Project has active runs or evaluations; cancellation was requested. Retry deletion shortly.': '项目存在进行中的运行或评测；已请求取消，请稍后重试删除。', 'No saved projects': '暂无已保存项目', 'Save the current design or start from a template.': '保存当前设计，或从模板开始。', 'New from template': '从模板新建',
  'Loading run detail': '正在加载运行详情', 'Run detail unavailable': '运行详情不可用', 'Node spans': '节点 Span', Node: '节点', Block: '积木', 'No spans recorded for this run.': '该运行没有记录节点 Span。',
  'Delete this evaluation and its recorded results?': '删除该评测及其记录的结果吗？', 'Remove assertion': '移除断言', 'Add assertion': '添加断言',
  'Custom text size': '自定义文字大小',
  'Manage projects': '管理项目', 'Revision loaded; save to keep it as a new version': '已加载该版本；保存后将成为新版本', 'Could not load revision': '无法加载该版本', 'Discard unsaved changes and load this revision?': '放弃未保存的更改并加载该版本吗？',
  'Delete version': '删除版本', 'The active version cannot be deleted': '当前使用的版本不能删除', 'Delete this version and its run records?': '删除该版本及其运行记录吗？', 'This version is referenced by an A/B evaluation, or is the only version — it cannot be deleted.': '该版本被 A/B 评测引用，或是唯一版本，无法删除。', 'Could not delete version': '无法删除版本',
  Connection: '连线', Route: '路由', 'Unconditional (any route)': '无条件（任意路由）', "Only the branch matching the Router's chosen route runs. Unconditional connections always run.": '只有与 Router 选中路由匹配的分支会执行；无条件连线始终执行。', 'Add routes to the Router block to branch this connection.': '在 Router 积木上添加 routes 才能给该连线分支。', 'Conditional routing applies to connections leaving a Router block.': '条件路由仅适用于从 Router 积木出发的连线。',
});

i18n.use(initReactI18next).init({
  resources: { en: { translation: {} }, 'zh-CN': { translation: zh } },
  lng: readLocale(), fallbackLng: 'en', keySeparator: false, interpolation: { escapeValue: false }, returnNull: false,
});
i18n.on('languageChanged', (language) => persistLocale(language === 'zh-CN' ? 'zh-CN' : 'en'));
persistLocale(i18n.language === 'zh-CN' ? 'zh-CN' : 'en');

export default i18n;
